# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='increase_by',
            field=models.PositiveIntegerField(default=200, verbose_name='\u0423\u0432\u0435\u043b\u0438\u0447\u0438\u0432\u0430\u0442\u044c \u0434\u0438\u0430\u043f\u0430\u0437\u043e\u043d \u043d\u0430'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='lower_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='\u0423\u0432\u0435\u043b\u0438\u0447\u0438\u0432\u0430\u0442\u044c \u0434\u0438\u0430\u043f\u0430\u0437\u043e\u043d \u043a\u0430\u0440\u0442 \u043f\u0440\u0438 \u0434\u043e\u0441\u0442\u0438\u0436\u0435\u043d\u0438\u0438 \u0438\u0445 \u0447\u0438\u0441\u043b\u0430'),
        ),
    ]
