# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20170309_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='card_letters',
            field=models.CharField(default='UTK', max_length=5, verbose_name='\u0411\u0443\u043a\u0432\u0435\u043d\u043d\u0430\u044f \u0447\u0430\u0441\u0442\u044c \u043a\u0430\u0440\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='lower_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='\u0423\u0432\u0435\u043b\u0438\u0447\u0438\u0432\u0430\u0442\u044c \u0434\u0438\u0430\u043f\u0430\u0437\u043e\u043d \u043a\u0430\u0440\u0442 \u043f\u0440\u0438 \u0434\u043e\u0441\u0442\u0438\u0436\u0435\u043d\u0438\u0438 \u0438\u0445 \u0447\u0438\u0441\u043b\u0430'),
        ),
    ]
